name: 'Test'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

env:
  REGISTRY_ACCESS_TOKEN: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
  REGISTRY_URL: ${{ secrets.REGISTRY_URL }}

jobs:
  test-notebooks:
    name: Test Notebooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install project dependencies
        run: |
          uv sync --only-dev

      - name: Register Jupyter kernel
        run: |
          python -m ipykernel install --user --name=python3

      - name: Run all notebooks
        run: |
          python .github/scripts/run_notebooks.py
