---
name: 'Test'
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test-notebooks:
    name: Test Notebooks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup project
        run: |
          pip install nbclient nbformat

      - name: Run notebooks
        run: |
          set -e
          for nb in $(find . -name "*.ipynb" -not -path "*/.ipynb_checkpoints/*"); do
            echo "🔍 Running $nb"
            python - <<EOF
          import nbformat
          from nbclient import NotebookClient

          with open("$nb") as f:
              nb = nbformat.read(f, as_version=4)

          client = NotebookClient(nb, timeout=600)
          client.execute()
          EOF
            echo "✅ Finished $nb"
          done
